# Listas de dicionários
usuarios = []
pedidos = []
alimentosBuscados = []
alimentos = [
{"nome": "pizza", "preco": 30, "categoria": "italiana"},
{"nome": "lasanha", "preco": 35, "categoria": "italiana"},
{"nome": "spaghetti", "preco": 28, "categoria": "italiana"},
{"nome": "ravioli", "preco": 32, "categoria": "italiana"},
{"nome": "gnocchi", "preco": 27, "categoria": "italiana"},
{"nome": "fettuccine", "preco": 29, "categoria": "italiana"},
{"nome": "calzone", "preco": 33, "categoria": "italiana"},
{"nome": "bruschetta", "preco": 15, "categoria": "italiana"},
{"nome": "tiramisu", "preco": 20, "categoria": "italiana"},
{"nome": "gelato", "preco": 18, "categoria": "italiana"},
{"nome": "feijoada", "preco": 25, "categoria": "brasileira"},
{"nome": "coxinha", "preco": 5, "categoria": "brasileira"},
{"nome": "pastel", "preco": 7, "categoria": "brasileira"},
{"nome": "pão de queijo", "preco": 4, "categoria": "brasileira"},
{"nome": "brigadeiro", "preco": 3, "categoria": "brasileira"},
{"nome": "quindim", "preco": 6, "categoria": "brasileira"},
{"nome": "acarajé", "preco": 12, "categoria": "brasileira"},
{"nome": "vatapá", "preco": 18, "categoria": "brasileira"},
{"nome": "moqueca", "preco": 35, "categoria": "brasileira"},
{"nome": "tapioca", "preco": 10, "categoria": "brasileira"},
{"nome": "sushi", "preco": 40, "categoria": "japonesa"},
{"nome": "temaki", "preco": 20, "categoria": "japonesa"},
{"nome": "yakisoba", "preco": 22, "categoria": "japonesa"},
{"nome": "ramen", "preco": 30, "categoria": "japonesa"},
{"nome": "onigiri", "preco": 8, "categoria": "japonesa"},
{"nome": "tempura", "preco": 25, "categoria": "japonesa"},
{"nome": "miso soup", "preco": 12, "categoria": "japonesa"},
{"nome": "okonomiyaki", "preco": 28, "categoria": "japonesa"},
{"nome": "sashimi", "preco": 35, "categoria": "japonesa"},
{"nome": "matcha ice cream", "preco": 15, "categoria": "japonesa"},
{"nome": "taco", "preco": 15, "categoria": "mexicana"},
{"nome": "burrito", "preco": 18, "categoria": "mexicana"},
{"nome": "guacamole", "preco": 12, "categoria": "mexicana"},
{"nome": "enchilada", "preco": 20, "categoria": "mexicana"},
{"nome": "quesadilla", "preco": 17, "categoria": "mexicana"},
{"nome": "nachos", "preco": 14, "categoria": "mexicana"},
{"nome": "churros", "preco": 6, "categoria": "mexicana"},
{"nome": "flan", "preco": 10, "categoria": "mexicana"},
{"nome": "sopa de tortilla", "preco": 16, "categoria": "mexicana"},
{"nome": "elote", "preco": 8, "categoria": "mexicana"},
{"nome": "kibe", "preco": 6, "categoria": "árabe"},
{"nome": "esfiha", "preco": 8, "categoria": "árabe"},
{"nome": "homus", "preco": 10, "categoria": "árabe"},
{"nome": "tabule", "preco": 12, "categoria": "árabe"},
{"nome": "babaganoush", "preco": 14, "categoria": "árabe"},
{"nome": "shawarma", "preco": 20, "categoria": "árabe"},
{"nome": "falafel", "preco": 15, "categoria": "árabe"},
{"nome": "manaqish", "preco": 18, "categoria": "árabe"},
{"nome": "baklava", "preco": 10, "categoria": "árabe"},
{"nome": "knafeh", "preco": 12, "categoria": "árabe"},
{"nome": "hamburguer", "preco": 20, "categoria": "lanche"},
{"nome": "hot dog", "preco": 12, "categoria": "lanche"},
{"nome": "batata frita", "preco": 10, "categoria": "lanche"},
{"nome": "sanduíche natural", "preco": 15, "categoria": "lanche"},
{"nome": "cheeseburger", "preco": 22, "categoria": "lanche"},
{"nome": "frango empanado", "preco": 18, "categoria": "lanche"},
{"nome": "onion rings", "preco": 12, "categoria": "lanche"},
{"nome": "nachos com queijo", "preco": 16, "categoria": "lanche"},
{"nome": "wrap de frango", "preco": 17, "categoria": "lanche"},
{"nome": "croissant", "preco": 8, "categoria": "lanche"},
{"nome": "pudim", "preco": 8, "categoria": "sobremesa"},
{"nome": "mousse de chocolate", "preco": 12, "categoria": "sobremesa"},
{"nome": "brownie", "preco": 10, "categoria": "sobremesa"},
{"nome": "bolo de cenoura", "preco": 9, "categoria": "sobremesa"},
{"nome": "cheesecake", "preco": 18, "categoria": "sobremesa"},
{"nome": "donut", "preco": 6, "categoria": "sobremesa"},
{"nome": "cupcake", "preco": 5, "categoria": "sobremesa"},
{"nome": "pavê", "preco": 14, "categoria": "sobremesa"},
{"nome": "sorvete", "preco": 12, "categoria": "sobremesa"},
{"nome": "torta de limão", "preco": 15, "categoria": "sobremesa"},
{"nome": "suco de laranja", "preco": 6, "categoria": "bebida"},
{"nome": "refrigerante", "preco": 5, "categoria": "bebida"},
{"nome": "cafe", "preco": 4, "categoria": "bebida"},
{"nome": "chá gelado", "preco": 5, "categoria": "bebida"},
{"nome": "vitamina de frutas", "preco": 10, "categoria": "bebida"},
{"nome": "agua mineral", "preco": 3, "categoria": "bebida"},
{"nome": "cerveja", "preco": 8, "categoria": "bebida"},
{"nome": "vinho", "preco": 25, "categoria": "bebida"},
{"nome": "smoothie", "preco": 12, "categoria": "bebida"},
{"nome": "chocolate quente", "preco": 7, "categoria": "bebida"},
{"nome": "salada caesar", "preco": 20, "categoria": "saudável"},
{"nome": "salada de frutas", "preco": 15, "categoria": "saudável"},
{"nome": "iogurte natural", "preco": 6, "categoria": "saudável"},
{"nome": "granola", "preco": 8, "categoria": "saudável"},
{"nome": "smoothie verde", "preco": 12, "categoria": "saudável"},
{"nome": "wrap de vegetais", "preco": 14, "categoria": "saudável"},
{"nome": "sopa de legumes", "preco": 18, "categoria": "saudável"},
{"nome": "frutas secas", "preco": 10, "categoria": "saudável"},
{"nome": "barra de cereais", "preco": 5, "categoria": "saudável"},
{"nome": "quinoa com legumes", "preco": 22, "categoria": "saudável"},
{"nome": "espaguete ao pesto", "preco": 28, "categoria": "italiana"},
{"nome": "focaccia", "preco": 18, "categoria": "italiana"},
{"nome": "panini", "preco": 20, "categoria": "italiana"},
{"nome": "polenta frita", "preco": 15, "categoria": "italiana"},
{"nome": "caponata", "preco": 16, "categoria": "italiana"},
{"nome": "ossobuco", "preco": 40, "categoria": "italiana"},
{"nome": "arancini", "preco": 14, "categoria": "italiana"},
{"nome": "frittata", "preco": 18, "categoria": "italiana"},
{"nome": "panna cotta", "preco": 17, "categoria": "italiana"},
{"nome": "gelatina italiana", "preco": 10, "categoria": "italiana"},
{"nome": "bobó de camarão", "preco": 35, "categoria": "brasileira"},
{"nome": "escondidinho", "preco": 22, "categoria": "brasileira"},
{"nome": "empadão", "preco": 18, "categoria": "brasileira"},
{"nome": "bolo de fubá", "preco": 8, "categoria": "brasileira"},
{"nome": "canjica", "preco": 7, "categoria": "brasileira"},
{"nome": "pamonha", "preco": 6, "categoria": "brasileira"},
{"nome": "bolo de rolo", "preco": 15, "categoria": "brasileira"},
{"nome": "tapioca doce", "preco": 9, "categoria": "brasileira"},
{"nome": "cuscuz paulista", "preco": 12, "categoria": "brasileira"},
{"nome": "sashimi de salmão", "preco": 38, "categoria": "japonesa"},
{"nome": "uramaki", "preco": 22, "categoria": "japonesa"},
{"nome": "temari sushi", "preco": 20, "categoria": "japonesa"},
{"nome": "sopa miso com tofu", "preco": 12, "categoria": "japonesa"},
{"nome": "gyoza", "preco": 18, "categoria": "japonesa"},
{"nome": "chirashi", "preco": 35, "categoria": "japonesa"},
{"nome": "donburi", "preco": 28, "categoria": "japonesa"},
{"nome": "takoyaki", "preco": 20, "categoria": "japonesa"},
{"nome": "mochi", "preco": 10, "categoria": "japonesa"},
{"nome": "taiyaki", "preco": 12, "categoria": "japonesa"},
{"nome": "enchiladas verdes", "preco": 18, "categoria": "mexicana"},
{"nome": "fajitas de frango", "preco": 20, "categoria": "mexicana"},
{"nome": "chilaquiles", "preco": 16, "categoria": "mexicana"},
{"nome": "tostadas", "preco": 14, "categoria": "mexicana"},
{"nome": "sopa azteca", "preco": 15, "categoria": "mexicana"},
{"nome": "molletes", "preco": 12, "categoria": "mexicana"},
{"nome": "pozole", "preco": 22, "categoria": "mexicana"},
{"nome": "empanadas mexicanas", "preco": 10, "categoria": "mexicana"},
{"nome": "tamales", "preco": 12, "categoria": "mexicana"},
{"nome": "agua de jamaica", "preco": 6, "categoria": "mexicana"},
{"nome": "shawarma de frango", "preco": 20, "categoria": "árabe"},
{"nome": "shawarma de carne", "preco": 22, "categoria": "árabe"},
{"nome": "tabule com tomate", "preco": 12, "categoria": "árabe"},
{"nome": "homus com tahine", "preco": 10, "categoria": "árabe"},
{"nome": "esfiha aberta", "preco": 9, "categoria": "árabe"},
{"nome": "kibe cru", "preco": 15, "categoria": "árabe"},
{"nome": "fatay", "preco": 13, "categoria": "árabe"},
{"nome": "manakish zaatar", "preco": 18, "categoria": "árabe"},
{"nome": "baklava pistache", "preco": 12, "categoria": "árabe"},
{"nome": "knafeh com queijo", "preco": 14, "categoria": "árabe"},
{"nome": "hamburguer duplo", "preco": 25, "categoria": "lanche"},
{"nome": "cheeseburger duplo", "preco": 28, "categoria": "lanche"},
{"nome": "frango frito picante", "preco": 20, "categoria": "lanche"},
{"nome": "hot dog duplo", "preco": 15, "categoria": "lanche"},
{"nome": "batata rústica", "preco": 12, "categoria": "lanche"},
{"nome": "mini hambúrguer", "preco": 10, "categoria": "lanche"},
{"nome": "sanduíche de atum", "preco": 18, "categoria": "lanche"},
{"nome": "wrap vegetariano", "preco": 16, "categoria": "lanche"},
{"nome": "croissant recheado", "preco": 9, "categoria": "lanche"},
{"nome": "bolo de chocolate", "preco": 12, "categoria": "sobremesa"},
{"nome": "bolo de baunilha", "preco": 10, "categoria": "sobremesa"},
{"nome": "pavlova", "preco": 15, "categoria": "sobremesa"},
{"nome": "creme brulee", "preco": 18, "categoria": "sobremesa"},
{"nome": "gelatina colorida", "preco": 8, "categoria": "sobremesa"},
{"nome": "sorvete de morango", "preco": 12, "categoria": "sobremesa"},
{"nome": "sorvete de chocolate", "preco": 12, "categoria": "sobremesa"},
{"nome": "pudim de leite", "preco": 10, "categoria": "sobremesa"},
{"nome": "mousse de maracujá", "preco": 12, "categoria": "sobremesa"},
{"nome": "suco de manga", "preco": 6, "categoria": "bebida"},
{"nome": "suco de abacaxi", "preco": 6, "categoria": "bebida"},
{"nome": "suco de morango", "preco": 6, "categoria": "bebida"},
{"nome": "suco detox", "preco": 8, "categoria": "bebida"},
{"nome": "suco verde", "preco": 8, "categoria": "bebida"},
{"nome": "água de coco", "preco": 7, "categoria": "bebida"},
{"nome": "limonada", "preco": 5, "categoria": "bebida"},
{"nome": "chá de camomila", "preco": 4, "categoria": "bebida"},
{"nome": "chá de hortelã", "preco": 4, "categoria": "bebida"},
{"nome": "salada de quinoa", "preco": 22, "categoria": "saudável"},
{"nome": "salada de grão de bico", "preco": 20, "categoria": "saudável"},
{"nome": "salada de lentilha", "preco": 18, "categoria": "saudável"},
{"nome": "tabule saudável", "preco": 15, "categoria": "saudável"},
{"nome": "smoothie de banana", "preco": 10, "categoria": "saudável"},
{"nome": "smoothie de morango", "preco": 10, "categoria": "saudável"},
{"nome": "smoothie de manga", "preco": 10, "categoria": "saudável"},
{"nome": "iogurte com frutas", "preco": 8, "categoria": "saudável"},
{"nome": "tigela de açaí", "preco": 18, "categoria": "saudável"},
{"nome": "panqueca integral", "preco": 12, "categoria": "saudável"},
{"nome": "omelete de legumes", "preco": 14, "categoria": "saudável"},
{"nome": "crepioca", "preco": 12, "categoria": "saudável"},
{"nome": "salada mediterrânea", "preco": 20, "categoria": "saudável"},
{"nome": "wrap de frango grelhado", "preco": 18, "categoria": "saudável"},
{"nome": "salada de rúcula e tomate", "preco": 15, "categoria": "saudável"},
{"nome": "espaguete integral", "preco": 25, "categoria": "saudável"},
{"nome": "lasanha de berinjela", "preco": 28, "categoria": "saudável"},
{"nome": "quiche de espinafre", "preco": 20, "categoria": "saudável"},
{"nome": "bolinho de grão de bico", "preco": 10, "categoria": "saudável"},
{"nome": "pizza vegetariana", "preco": 30, "categoria": "italiana"},
{"nome": "pizza de calabresa", "preco": 32, "categoria": "italiana"},
{"nome": "pizza quatro queijos", "preco": 35, "categoria": "italiana"},
{"nome": "pizza marguerita", "preco": 28, "categoria": "italiana"},
{"nome": "lasanha bolonhesa", "preco": 36, "categoria": "italiana"},
{"nome": "lasanha de frango", "preco": 34, "categoria": "italiana"},
{"nome": "spaghetti ao alho e óleo", "preco": 26, "categoria": "italiana"},
{"nome": "gnocchi ao molho branco", "preco": 29, "categoria": "italiana"},
{"nome": "ravioli de ricota", "preco": 31, "categoria": "italiana"},
{"nome": "fettuccine alfredo", "preco": 30, "categoria": "italiana"},
{"nome": "calzone de presunto", "preco": 33, "categoria": "italiana"},
{"nome": "bruschetta de tomate", "preco": 15, "categoria": "italiana"},
{"nome": "tiramisu de chocolate", "preco": 20, "categoria": "italiana"},
{"nome": "gelato de morango", "preco": 18, "categoria": "italiana"},
{"nome": "gelato de chocolate", "preco": 18, "categoria": "italiana"}
]